=== ShilovAndrey/LearningJava/src/xmlParser/XmlTest/xmlDomParser/company_staff_schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="company">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="company_name" type="xs:string"/>
                <xs:element name="departments" type="departments"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="departments">
        <xs:sequence>
            <xs:element name="department" type="department" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="department">
        <xs:sequence>
            <xs:element name="employee" type="employee" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="dept_name">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="administration"/>
                    <xs:enumeration value="IT"/>
                    <xs:enumeration value="security"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="employee">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="age" type="xs:integer"/>
            <xs:element name="gender" type="gender"/>
            <xs:element name="salary" type="salary"/>
        </xs:sequence>
        <xs:attribute name="id_number" type="xs:integer"/>
    </xs:complexType>

    <xs:simpleType name="gender">
        <xs:restriction base="xs:string">
            <xs:enumeration value="m"/>
            <xs:enumeration value="f"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="salary">
        <xs:complexContent>
            <xs:restriction base="xs:integer">
                <xs:attribute name="currency">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="doll"/>
                            <xs:enumeration value="euro"/>
                            <xs:enumeration value="rub"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:restriction>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>

=== ShilovAndrey/LearningJava/src/xmlParser/XmlTest/company_staff.xml
<?xml version="1.0" encoding="UTF-8" ?>
<company xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
         xs:noNamespaceSchemaLocation="company_staff_schema.xsd">
    <company_name>Shilov Industry</company_name>
    <departments>
        <department dept_name="administration">
            <employee id_number="1">
                <name>Shilov Andrey</name>
                <age>32</age>
                <gender>m</gender>
                <salary currency="doll">20000</salary>
            </employee>
            <employee id_number="2">
                <name>John Malic</name>
                <age>35</age>
                <gender>m</gender>
                <salary currency="doll">20000</salary>
            </employee>
        </department>
        <department dept_name="IT">
            <employee id_number="3">
                <name>Frank Prithard</name>
                <age>43</age>
                <gender>m</gender>
                <salary currency="doll">10000</salary>
            </employee>
            <employee id_number="4">
                <name>Stack Tokan</name>
                <age>28</age>
                <gender>m</gender>
                <salary currency="doll">2000</salary>
            </employee>
            <employee id_number="7">
                <name>Anna Adams</name>
                <age>28</age>
                <gender>f</gender>
                <salary currency="doll">1500</salary>
            </employee>
        </department>
        <department dept_name="security">
            <employee id_number="5">
                <name>Adam Jensen</name>
                <age>41</age>
                <gender>m</gender>
                <salary currency="doll">10000</salary>
            </employee>
            <employee id_number="6">
                <name>Nick Jons</name>
                <age>31</age>
                <gender>m</gender>
                <salary currency="doll">2000</salary>
            </employee>
            <employee id_number="8">
                <name>Lena Moon</name>
                <age>32</age>
                <gender>f</gender>
                <salary currency="doll">2000</salary>
            </employee>
            <employee id_number="9">
                <name>Dana Scaly</name>
                <age>45</age>
                <gender>f</gender>
                <salary currency="doll">3500</salary>
            </employee>
        </department>
    </departments>
</company>
